/*
 * CortexM4_CORE_Systic_CFG.h
 *
 *  Created on: Feb 12, 2025
 *      Author: Mohamed Tarek
 */

#ifndef CORTEXM4_CORTEXM4_CORE_SYSTIC_CFG_H_
#define CORTEXM4_CORTEXM4_CORE_SYSTIC_CFG_H_

#define SYSTIC_EXTERNAL_CLOCK		0
#define SYSTIC_CORE_CLOCK			1

#define SYSTIC_CLOCK				SYSTIC_EXTERNAL_CLOCK


#endif /* CORTEXM4_CORTEXM4_CORE_SYSTIC_CFG_H_ */
